global_frame: map
static_map: false
rolling_window: true
track_unknown_space: true
width: 100.0
height: 100.0

plugins:
  - {name: obstacles_laser,         type: "costmap_2d::ObstacleLayer"}
  - {name: inflation,               type: "costmap_2d::InflationLayer"}