# footprint: [[-0.5, -0.45], [-0.5, 0.45], [0.5, 0.45], [0.5, -0.45]]
footprint: [[-0.2, -0.15], [-0.2, 0.15], [0.2, 0.15], [0.2, -0.15]]
footprint_padding: 0.01

robot_base_frame: fake
update_frequency: 3.0
publish_frequency: 2.0
transform_tolerance: 0.2

resolution: 0.05

obstacle_range: 12.0
raytrace_range: 12.0

obstacles_laser:
  observation_sources: point_cloud_sensor
  point_cloud_sensor: {
    data_type: PointCloud2,
    clearing: true,
    marking: true,
    topic: points_filtered,
    max_obstacle_height: 1.5,
    min_obstacle_height: 0.05
  }

inflation:
  inflation_radius: 0.08